substitutions:
  _ENV: dev

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'hashicorp/terraform:1.8.0'
    entrypoint: sh
    args:
      - -c
      - |
          set -e

          echo "Initializing Terraform..."
          terraform init -backend-config="envs/${_ENV}/backend.config" -reconfigure

          echo "Switching to workspace: ${_ENV}"
          terraform workspace select ${_ENV} || terraform workspace new ${_ENV}

          echo "Running Terraform Plan..."
          terraform plan -lock-timeout=60s -var-file="envs/${_ENV}/terraform.tfvars" -out=tfplan.binary

          echo "Applying Terraform Plan..."
          terraform apply -lock-timeout=60s -auto-approve tfplan.binary