steps:
  - name: 'hashicorp/terraform:1.8.0'
    entrypoint: sh
    args: 
      - -c
      - |
          terraform init
          terraform apply -auto-approve -var-file="envs/${_ENV}/terraform.tfvars"
      
substitutions:
  _ENV: dev

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s