steps:
  - name: 'hashicorp/terraform:1.8.0'
    entrypoint: sh
    args:
      - -c
      - |
          terraform init -backend-config="envs/${_ENV}/backend.config" -reconfigure
          terraform workspace select ${_ENV} || terraform workspace new ${_ENV}
          terraform apply -auto-approve -var-file="envs/${_ENV}/terraform.tfvars"

substitutions:
  _ENV: dev  

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s